<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>
		<?php
		echo esc_html(
			sprintf(
				/* translators: %s: email subject or name */
				__( 'New Contact Form Submission: %s', 'am-portfolio-theme' ),
				! empty( $data['subject'] ) ? $data['subject'] : $data['name']
			)
		);
		?>
	</title>
	
	<?php get_template_part( 'templates/emails/partials/styles' ); ?>
	
	<style>
		.cta-button {
			background-color: #06f;
			color: #fff;
			padding: 12px 24px;
			text-decoration: none;
			border-radius: 8px;
			display: inline-block;
			font-weight: 600;
		}

		.cta-button:hover {
			background-color: #0052cc;
		}

		@media (prefers-color-scheme: dark) {
			.cta-button {
				background-color: #4d94ff;
			}

			.cta-button:hover {
				background-color: #3a7bd9;
			}
		}
	</style>
</head>
<body>
	<div class="email-container">
		<div class="email-header">
			<h1><?php echo esc_html( __( 'New Contact Form Submission', 'am-portfolio-theme' ) ); ?></h1>
		</div>

		<div class="email-body">
			<div class="timestamp">
				<?php
				printf(
					/* translators: 1: date, 2: time */
					esc_html__( 'Received on %1$s at %2$s', 'am-portfolio-theme' ),
					esc_html( $data['date'] ),
					esc_html( $data['time'] )
				);
				?>
			</div>

			<?php
				$email_data = array_merge(
					$data,
					array(
						'show_language' => true,
						'show_timezone' => true,
					)
				);
				set_query_var( 'email_data', $email_data );
				get_template_part( 'templates/emails/partials/submission-details' );
				?>

			<?php if ( ! empty( $data['admin_url'] ) ) : ?>
				<div style="text-align: center; margin-top: 32px">
					<a href="<?php echo esc_url( $data['admin_url'] ); ?>" class="cta-button">
						<?php echo esc_html( __( 'View in Admin Dashboard', 'am-portfolio-theme' ) ); ?>
					</a>
				</div>
			<?php endif; ?>
		</div>

		<div class="email-footer">
			<p>
				<?php echo esc_html( __( 'This email was automatically generated by your portfolio website contact form.', 'am-portfolio-theme' ) ); ?>
			</p>
			<p><?php echo esc_html( __( 'Please do not reply to this message.', 'am-portfolio-theme' ) ); ?></p>
		</div>
	</div>
</body>
</html>